jenkins:
 user: root
 tty: true
 stdin_open: true
 image: arma_sheep_server/jenkins
 container_name: jenkins
 ports:
  - 8083:8080
  - 50000:50000
 volumes:
  - jenkins-data:/var/jenkins_home/
  - /var/run/docker.sock:/var/run/docker.sock
